import{S as q,i as f,a as C}from"./assets/vendor-b52d9f5e.js";(function(){const c=document.createElement("link").relList;if(c&&c.supports&&c.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const m of t.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&d(m)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const h=document.querySelector(".searchForm"),c=document.querySelector(".searchInput"),l=document.querySelector(".loader"),d=document.querySelector(".gallery"),e=document.querySelector(".load-more-button"),t="42055816-5ec499474650eadfc6b07a02f",m="https://pixabay.com/api/",y=40,w=new q(".gallery a",{captionDelay:250,captionsData:"alt"});let g=1,p=[];h.addEventListener("submit",async i=>{i.preventDefault();const r=c.value.trim();if(p=[],p.push(r),r===""){f.error({title:"Error",position:"topRight",message:"Please enter a search term."});return}l.classList.remove("hidden"),d.innerHTML="",e.classList.add("hidden"),g=1;try{await L(r,g)}catch(s){console.error("Error fetching data:",s),f.error({title:"Error",position:"topRight",message:"An error occurred while fetching data. Please try again."})}finally{l.classList.add("hidden")}h.reset()}),e.addEventListener("click",()=>{l.classList.remove("hidden"),e.classList.add("hidden"),g++,L(p,g)});async function L(i,r=1){try{const s=await C.get(`${m}?key=${t}&q=${i}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${y}`);if(s.status!==200)throw new Error(`HTTP error! Status: ${s.status}`);const a=s.data;if(a.hits.length===0)e.classList.add("hidden"),f.show({title:"End of Collection",messageColor:"#fff",messageSize:"20px",backgroundColor:"#EF4040",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"});else{const o=a.hits.map(n=>({webformatURL:n.webformatURL,largeImageURL:n.largeImageURL,tags:n.tags,likes:n.likes,views:n.views,comments:n.comments,downloads:n.downloads}));v(o),a.totalHits>r*y?e.classList.remove("hidden"):(e.classList.add("hidden"),f.show({title:"End of Collection",messageColor:"#fff",messageSize:"20px",backgroundColor:"#EF4040",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}}catch(s){console.error("Error fetching data:",s),f.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}finally{l.classList.add("hidden")}}function v(i){var a;const r=i.map(o=>`
          <div class="gallery-item">
            <a href="${o.largeImageURL}" data-lightbox="gallery" data-title="${o.tags}">
              <img src="${o.webformatURL}" alt="${o.tags}" class="image-thumbnail">
            </a>
            <div class="image-details">
              <p><b>Likes:</b> ${o.likes}</p>
              <p><b>Views:</b> ${o.views}</p>
              <p><b>Comments:</b> ${o.comments}</p>
              <p><b>Downloads:</b> ${o.downloads}</p>
            </div>
          </div>
        `).join("");d.innerHTML+=r,w.refresh();const s=(a=document.querySelector(".gallery-item"))==null?void 0:a.getBoundingClientRect().height;s&&E(s*i.length,5500)}function E(i,r){const s=window.scrollY;let a=null;function o(n){a||(a=n);const b=n-a,S=Math.min(b,r),$=u=>u<.5?2*u*u:-1+(4-2*u)*u;window.scrollTo(0,s+$(S/r)*i),b<r&&requestAnimationFrame(o)}requestAnimationFrame(o)}});
//# sourceMappingURL=commonHelpers.js.map
