import{S as R,i as f,a as S}from"./assets/vendor-b52d9f5e.js";(function(){const l=document.createElement("link").relList;if(l&&l.supports&&l.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const g=document.querySelector(".searchForm"),l=document.querySelector(".searchInput"),c=document.querySelector(".loader"),d=document.querySelector(".gallery"),e=document.querySelector(".load-more-button"),t="42055816-5ec499474650eadfc6b07a02f",u="https://pixabay.com/api/",p=15,b=new R(".gallery a",{captionDelay:250,captionsData:"alt"});let h=1;g.addEventListener("submit",async i=>{i.preventDefault();const s=l.value.trim();if(s===""){f.error({title:"Error",position:"topRight",message:"Please enter a search term."});return}c.classList.remove("hidden"),d.innerHTML="",e.classList.add("hidden");try{await y(s,h)}catch(o){console.error("Error fetching data:",o),f.error({title:"Error",position:"topRight",message:"An error occurred while fetching data. Please try again."})}finally{c.classList.add("hidden")}}),e.addEventListener("click",()=>{c.classList.remove("hidden"),e.classList.add("hidden"),h++,y(l.value.trim(),h)});async function y(i,s){try{const o=await S.get(`${u}?key=${t}&q=${i}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=${p}`);if(o.status!==200)throw new Error(`HTTP error! Status: ${o.status}`);const a=o.data;if(a.hits.length===0)e.classList.add("hidden"),f.info({title:"End of Collection",position:"topRight",message:"We're sorry, but you've reached the end of search results."});else{const r=a.hits.map(n=>({webformatURL:n.webformatURL,largeImageURL:n.largeImageURL,tags:n.tags,likes:n.likes,views:n.views,comments:n.comments,downloads:n.downloads}));w(r),a.totalHits>s*p?e.classList.remove("hidden"):e.classList.add("hidden")}}catch(o){console.error("Error fetching data:",o),f.error({title:"Error",position:"topRight",message:"An error occurred while fetching data. Please try again."})}finally{c.classList.add("hidden")}}function w(i){var a;const s=i.map(r=>`
          <div class="gallery-item">
            <a href="${r.largeImageURL}" data-lightbox="gallery" data-title="${r.tags}">
              <img src="${r.webformatURL}" alt="${r.tags}" class="image-thumbnail">
            </a>
            <div class="image-details">
              <p><b>Likes:</b> ${r.likes}</p>
              <p><b>Views:</b> ${r.views}</p>
              <p><b>Comments:</b> ${r.comments}</p>
              <p><b>Downloads:</b> ${r.downloads}</p>
            </div>
          </div>
        `).join("");d.innerHTML+=s,b.refresh();const o=(a=document.querySelector(".gallery-item"))==null?void 0:a.getBoundingClientRect().height;o&&v(o*i.length,300)}function v(i,s){const o=window.scrollY;let a=null;function r(n){a||(a=n);const L=n-a,$=Math.min(L,s),E=m=>m<.5?2*m*m:-1+(4-2*m)*m;window.scrollTo(0,o+E($/s)*i),L<s&&requestAnimationFrame(r)}requestAnimationFrame(r)}});
//# sourceMappingURL=commonHelpers.js.map
