import{S as q,i as f,a as C}from"./assets/vendor-b52d9f5e.js";(function(){const c=document.createElement("link").relList;if(c&&c.supports&&c.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&d(m)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();document.addEventListener("DOMContentLoaded",()=>{const p=document.querySelector(".searchForm"),c=document.querySelector(".searchInput"),l=document.querySelector(".loader"),d=document.querySelector(".gallery"),e=document.querySelector(".load-more-button"),o="42055816-5ec499474650eadfc6b07a02f",m="https://pixabay.com/api/",L=39,w=new q(".gallery a",{captionDelay:250,captionsData:"alt"});let h=1,y=[];p.addEventListener("submit",async i=>{i.preventDefault();const r=c.value.trim();if(y=[],y.push(r),r===""){f.error({title:"Error",position:"topRight",message:"Please enter a search term."});return}l.classList.remove("hidden"),d.innerHTML="",e.classList.add("hidden"),h=1;try{await b(r,h)}catch(s){console.error("Error fetching data:",s),f.error({title:"Error",position:"topRight",message:"An error occurred while fetching data. Please try again."})}finally{l.classList.add("hidden")}p.reset()}),e.addEventListener("click",()=>{l.classList.remove("hidden"),e.classList.add("hidden"),h++,b(y,h)});async function b(i,r=1){try{const s=new URLSearchParams({key:o,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:L}),a=await C.get(`${m}?${s}`);if(a.status!==200)throw new Error(`HTTP error! Status: ${a.status}`);const t=a.data;if(t.hits.length===0)e.classList.add("hidden"),f.show({title:"End of Collection",messageColor:"#fff",messageSize:"20px",backgroundColor:"#EF4040",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"});else{const g=t.hits.map(n=>({webformatURL:n.webformatURL,largeImageURL:n.largeImageURL,tags:n.tags,likes:n.likes,views:n.views,comments:n.comments,downloads:n.downloads}));v(g),t.totalHits>r*L?e.classList.remove("hidden"):(e.classList.add("hidden"),f.show({title:"End of Collection",messageColor:"#fff",messageSize:"20px",backgroundColor:"#EF4040",message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}))}}catch(s){console.error("Error fetching data:",s),f.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}finally{l.classList.add("hidden")}}function v(i){var a;const r=i.map(t=>`
          <div class="gallery-item">
            <a href="${t.largeImageURL}" data-lightbox="gallery" data-title="${t.tags}">
              <img src="${t.webformatURL}" alt="${t.tags}" class="image-thumbnail">
            </a>
            <div class="image-details">
              <p><b>Likes:</b> ${t.likes}</p>
              <p><b>Views:</b> ${t.views}</p>
              <p><b>Comments:</b> ${t.comments}</p>
              <p><b>Downloads:</b> ${t.downloads}</p>
            </div>
          </div>
        `).join("");d.innerHTML+=r,w.refresh();const s=(a=document.querySelector(".gallery-item"))==null?void 0:a.getBoundingClientRect().height;s&&E(s*i.length,17500)}function E(i,r){const s=window.scrollY;let a=null;function t(g){a||(a=g);const n=g-a,S=Math.min(n,r),R=u=>u<.5?2*u*u:-1+(4-2*u)*u;window.scrollTo(0,s+R(S/r)*i),n<r&&requestAnimationFrame(t)}requestAnimationFrame(t)}});
//# sourceMappingURL=commonHelpers.js.map
